# Generated by Django 3.1 on 2020-08-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User_Model',
        ),
    ]
