# Generated by Django 3.1 on 2020-08-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_auto_20200816_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=10)),
                ('user_address', models.CharField(max_length=100)),
                ('ordered_items', models.CharField(max_length=20)),
            ],
        ),
    ]
