# Generated by Django 3.1 on 2020-08-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_order_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_model',
            name='order_status',
            field=models.CharField(default='pending', max_length=10),
            preserve_default=False,
        ),
    ]
